### ISSUE TITLE
Run compilation steps once, and copy binary to run tests in parallel

### ISSUE THREAD

**Issue by notriddle** [servo/saltfs#498] opened 2016-09-29 20:03 UTC
Currently, parallel steps like mac-rel-wpt and mac-rel-css compile Servo separately before running it on both of the machines. Fixing this won't speed up the simple linear case, but it will help when there's a try build and an auto build running concurrently (they'll be able to compile in parallel).

**Comment by aneeshusa** [comment] 2016-09-29 20:07
This is definitely a good idea that I've looked at in the past. I believe the best way to do this is via [Transfer build steps](https://docs.buildbot.net/0.8.12/manual/cfg-buildsteps.html#transferring-files) to do this. However, I'm not sure of a good way to fit this into the current yaml-based build step declaration, so this will require some more thinking.

**Comment by aneeshusa** [comment] 2016-09-29 20:10
@larsbergstrom's [suggestion](https://github.com/servo/saltfs/pull/497#issuecomment-250576342) of [Dependent schedulers](https://docs.buildbot.net/0.8.12/manual/cfg-schedulers.html#dependent-scheduler) also looks like a key component of this.

**Comment by aneeshusa** [comment] 2016-09-29 20:18
An alternative to uploading builds to the buildmaster is to upload them to S3. This could also make it easier to make a version of [mozregression](https://github.com/mozilla/mozregression) for Servo, which has been requested in the past.

**Comment by notriddle** [comment] 2016-09-29 21:55
Are we currently actually using the YAML builders?

**Comment by aneeshusa** [comment] 2016-09-29 22:24
Yes, buildbot currently reads from [this file in saltfs](https://github.com/servo/saltfs/blob/master/buildbot/master/files/config/steps.yml) (as deployed on the buildbot master).

**Comment by metajack** [comment] 2016-10-03 01:32
I looked into this before quite a while back. As far as I can tell making build rules that trigger on file uploads is not really possible in Buildbot. This is something that taskcluster can do.

The only thing I've been able to think of so far is to upload the build artifact to s3 and have some other bot be notified of completion by buildbot and then trigger a second job to download/run tests.

**Comment by aneeshusa** [comment] 2016-10-03 01:41
@metajack, the docs seem to indicate Dependent Schedulers will handle this in Buildbot, letting you trigger a build when another build finishes. We can have the first build end with the file upload step, and Buildbot should kick off the next builds after that one finishes.

**Comment by metajack** [comment] 2016-10-03 01:54
That sounds great then. It seems like we could split the yaml steps into build steps and test steps, probably multiple pairs of them,, and then have buildbot do this two step process.

**Comment by SimonSapin** [comment] 2018-11-30 13:51
https://github.com/servo/servo/pull/21776 implemented this. It will be effective when we enable WPT on Taskcluster and disable it on Buildbot. CC https://github.com/servo/servo/issues/22325

**Closed by SimonSapin** 2018-11-30 13:51 UTC
Labels: enhancement
